Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -114,11 +114,11 @@ jobs:
       - run:
           name: Smoke Test
           command: | 
-          HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://agile-coast-99905.herokuapp.com/`
-          if [ "$HTTPCODE" -ne 200 ];then
-            echo "heroku app not responding, failing deploy"
-            exit 1
-          fi
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://agile-coast-99905.herokuapp.com/`
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "heroku app not responding, failing deploy"
+              exit 1
+            fi
 
 workflows:
   version: 2
